### PR TITLE
Update MoToESP32.cpp to support Espressif core 3.0.3

### PR DESCRIPTION
**Pull request by zs6buj**
Hi Franz-Peter, herewith a PR to update MoToESP32 to work with Espressif core 3.0.3. I commented out the obsolete function, and inserted the new ones underneath. It clean compiles here, and runs my slightly modified Servo02 example properly.

This pertains to the issue we discussed previously.

Eric Stockentrom
zs6buj

### CODE REVIEW

**Comment by MicroBahner** [comment]
Hi Eric,
thank you for your contribution. I will give it a try and report back. But it may need a couple of days, because i'm busy with some other Projects at the moment.
Franz-Peter

**Comment by zs6buj** [comment]
Hi Franz-Peter, since posting this PR, I have determined during testing that MotoToESP32.cpp line 52 should be

`       stepTimer = timerBegin(2000000);  // frequency`

My apologies.

**Comment by MicroBahner** [comment]
Hi Eric,
yes, I tested your pull request and it didn't work at a first try. Now, with this change in line 52 the motor is turning. Thanks.
I will do some further testing and try to get it working with esp V2 and V3. 
Because V3  interferes with many other libraries too, I know that many users still use V2.
Then I will create a patch version for the library manager.

**Comment by zs6buj** [comment]
Thank you for dealing with this now. I understand you are also busy with other things

**Comment by MicroBahner** [comment]
Hi Eric,
I have updated the master branch as a release candidate for V2.6.2.
Maybe you can test if it meets your needs. It should work with the V2 and V3 core.
I will also do some more testing with my standard test sketches.
Franz-Peter

**Comment by zs6buj** [comment]
Great, thank you Franz-Peter. I'll be able to test within the next few days

**Comment by zs6buj** [comment]
It is working nicely here now, thank you Franz-Peter

**Comment by MicroBahner** [comment]
Hello Eric,
thanks for your feedback. I am in the process of fixing another bug (issue#34), then I will create a new version for the library manager. 
But I'm not quite sure if I can do it before my vacation. Fixing this bug is a bit difficult because it only happens with an exact timing coincide of two events. So maybe it will take until afterwards.
Regards, franz-Peter

**Comment by zs6buj** [comment]
Hello Franz-Peter, thank you for the feedback. There is no hurry as my patched version is working satisfactorily for me. Enjoy your vacation.

**Comment by MicroBahner** [comment]
Thanks, I'll let you know when I release V2.6.2.

**Comment by MicroBahner** [comment]
V2.6.2 is released now.
Thanks for your contribution.

**Comment by zs6buj** [comment]
Thanks for the update Franz-Peter. It's working perfectly here.

**Pull request merged**
